config/routes.rb
ResourceManager::Application.routes.draw do
  
  get "comments/create"

  resources :users
  resources :resources
  resources :meetings do
    resources :comments
  end
  resources :sessions
  
  get "home/Index"
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  get "current_resource" => "resources#show_current", :as => "current_resource"
  get "edit_current" => "resources#edit_current", :as => "edit_current"
  get "set_current" => "application#add_resource_to_session", :as => "set_current"
  root :to => "home#index"
    

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :username, :first_name, :last_name, :email, :serial_number, :password, :password_confirmation

  attr_accessor :password
  before_save :encrypt_password

  validates :password, :confirmation => true,
                       :presence => true, :on => :create,
                       :length => { :in => 8..20 }
  validates :username, :presence => true,
                       :uniqueness => true
  validates :first_name, :presence => true
  validates :last_name, :presence => true
  validates :email, :presence => true,
                    :uniqueness => true
  validates :serial_number, :presence => true,
                     :uniqueness => true
  has_many :resources
 
  def self.authenticate(username, password)
    user = find_by_username(username)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end

  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user
  helper_method :current_resource
  helper_method :add_resource_to_session
  before_filter :require_login
  
  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  def require_login
    unless current_user
      redirect_to log_in_path
    end
  end
  
  def current_resource
    @current_resource ||= Resource.find(session[:resource_id]) if session[:resource_id]
  end

  def add_resource_to_session
    session[:resource_id] = params[:id] if params[:id] != nil
  end
  
  def require_resource
    unless current_resource
      redirect_to resources_path
      flash.now.alert = "Please Select a Resource!"
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_filter :require_login
  
  def new
  end

  def create
    user = User.authenticate(params[:username], params[:password])
    if user
      session[:user_id] = user.id
      redirect_to root_url, :notice => "Logged in!"
    else
      flash.now.alert = "Invalid email or password"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    session[:resource_id] = nil
    redirect_to root_url, :notice => "Logged out!"
  end

  def add_resource_to_session
    session[:resource_id] = params[:id] if params[:id] != nil
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :require_login
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to root_url, :notice => "Signed up!"
    else
      render "new"
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_message_display.html.haml
%div.app_message
 - flash.each do |name, msg|
  = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_user_nav.html.haml
%div#user_nav
 - if current_user
  Logged in as
  = current_user.username
  = link_to "Log out", log_out_path
 - else
  = link_to "Sign up", sign_up_path
  or
  = link_to "log in", log_in_path

app/views/layouts/application.html.haml
!!! 5
%html
 %head
  %title
   Resource Manager
  = stylesheet_link_tag    "application"
  = javascript_include_tag "application"
  = csrf_meta_tags
 %body
  %div.titlebar
   = render "layouts/menubar"
   = render "layouts/user_nav"
  = render "layouts/message_display"
  = yield

app/views/users/_new_user_form.html.haml
%div.user_form
 = form_for @user do |f|
  - if @user.errors.any?
   %div.error_messages
    %h2
     Form is invalid
    %ul
     - for message in @user.errors.full_messages
      %li>
       = message
  %div.user_info_header
   %h2
    User Information
   %div.user_info
    %p
     = f.label :first_name
     %br/
     = f.text_field :first_name
    %p
     = f.label :last_name
     %br/
     = f.text_field :last_name
    %p
     = f.label :serial_number
     %br/
     = f.text_field :serial_number
    %p
     = f.label :email
     %br/
     = f.text_field :email
  %div.account_info_header
   %h2
    Account Information
   %div.account_info
    %p
     = f.label :username
     %br/
     = f.text_field :username
    %p
     = f.label :password
     %br/
     = f.password_field :password
    %p
     = f.label :password_confirmation
     %br/
     = f.password_field :password_confirmation
  %p.button
   = f.submit

app/views/users/new.html.haml
%div.signup
 %h1
  Sign Up
 = render "users/new_user_form"